name: deploy-to-gcp

on:
  push:
    branches: [prod]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: create-react-app
  REGION: us-central1
  python-version: '3.9'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${PROJECT_ID}/carpool_service_test .
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io
          docker push gcr.io/${PROJECT_ID}/carpool_service_test

      - name: Deploy to Cloud Run
        uses: GoogleCloudPlatform/github-actions/cloud-run@main
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${PROJECT_ID}/carpool_service_test
          platform: managed
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          CLOUD_RUN_REGION: ${{ env.REGION }}

      - name: Info
        run: gcloud info
