name: unit-test

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: carpool-service-backend-unitest
  REGION: asia-east1
  PYTHON_VERSION: '3.9'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install pytest
        run:
          pip3 install -r requirements.txt 

      - name: build test docker
        run:
          docker build -t unit_test:01 .

      - name: run test docker
        run:
          docker run -d -p 8080:8080 unit_test:01

      - name: sleep
        run:
          sleep 10

      - name: pytest
        run:
          pytest unit_test.py

      - name: test docker stop
        run:
          docker stop $(docker ps -a -q)

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01 .
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01